# Generated by Django 3.1.2 on 2020-10-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods_api', '0002_auto_20201024_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.TextField(),
        ),
    ]
